"""
Chicago Golf Course Configuration — 40 Courses
Source of truth for all course metadata, booking URLs, platforms, and policies.
"""


def _gn(fid, name_slug):
    """Build GolfNow URL from facility ID and name slug."""
    return f"https://www.golfnow.com/tee-times/facility/{fid}-{name_slug}/search"


COURSES = {
    # ===== ORIGINAL A-GROUP (14 courses) =====

    "bolingbrook": {
        "name": "Bolingbrook Golf Club",
        "tier": "A+", "platform": "golfnow",
        "booking_url": _gn(734, "bolingbrook-golf-club"),
        "direct_url": "https://bolingbrook.ezlinksgolf.com",
        "chronogolf_url": "https://www.chronogolf.com/club/bolingbrook-golf-club",
        "golfnow_facility_id": "734",
        "phone": "(630) 771-9400",
        "distance_miles": 34, "direction": "SW",
        "advance_booking_days": 14, "has_range": True, "range_included": True,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "Free cancel 24hr+. CC guarantee only. No-show charged.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "KemperSports",
        "noteefy_available": True, "autobook_eligible": True,
        "notes": "Basically private club amenities for public. Dynamic pricing. Free range with round. LIV Golf venue.",
    },
    "harborside": {
        "name": "Harborside International",
        "tier": "A+", "platform": "golfnow",
        "booking_url": _gn(1108, "harborside-international-port-course"),
        "direct_url": "https://harborsidegolf.com",
        "golfnow_facility_id": "1108",
        "phone": "(312) 782-7837",
        "distance_miles": 15, "direction": "S",
        "advance_booking_days": 21, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "Free cancel 24hr+. CC guarantee.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": ["Port", "Starboard"], "management": "City of Chicago",
        "noteefy_available": True, "autobook_eligible": True,
        "notes": "Two championship courses. Port is the flagship. Close to city.",
    },
    "stonewall": {
        "name": "Stonewall Orchard Golf Club",
        "tier": "A+", "platform": "golfnow",
        "booking_url": _gn(11392, "stonewall-orchard"),
        "direct_url": "https://www.stonewallorchard.com",
        "golfnow_facility_id": "11392",
        "phone": "(847) 740-4890",
        "distance_miles": 45, "direction": "NW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "Free cancel 24hr+. CC guarantee.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "KemperSports",
        "noteefy_available": True, "autobook_eligible": True,
        "notes": "Arthur Hills design. Former host of USGA qualifiers.",
    },
    "thunderhawk": {
        "name": "Thunderhawk Golf Club",
        "tier": "A+", "platform": "golfnow",
        "booking_url": _gn(7739, "thunderhawk-golf-club"),
        "direct_url": "https://www.thunderhawkgolf.com",
        "golfnow_facility_id": "7739",
        "phone": "(847) 968-4295",
        "distance_miles": 50, "direction": "N",
        "advance_booking_days": 30, "has_range": True, "range_included": True,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "Free cancel 24hr+.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Lake County Forest Preserve",
        "noteefy_available": True, "autobook_eligible": True,
        "notes": "Robert Trent Jones Jr design. Wide open links-style.",
    },
    "schaumburg": {
        "name": "Schaumburg Golf Club",
        "tier": "A", "platform": "golfnow",
        "booking_url": _gn(727, "schaumburg-golf-club"),
        "direct_url": "https://www.schaumburggolf.com",
        "golfnow_facility_id": "727",
        "phone": "(847) 885-9000",
        "distance_miles": 30, "direction": "NW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "Free cancel 24hr+.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": ["Tournament", "Players", "Baer"],
        "management": "Schaumburg Park District",
        "noteefy_available": True, "autobook_eligible": True,
        "notes": "27 holes. Tournament course is the main draw.",
    },
    "preserve_oak": {
        "name": "Preserve at Oak Meadows",
        "tier": "A+", "platform": "chronogolf",
        "booking_url": "https://www.dupagegolf.com/preserve",
        "direct_url": "https://www.dupagegolf.com/preserve",
        "chronogolf_url": "https://www.chronogolf.com/club/oak-meadows-golf-course",
        "golfnow_facility_id": None,
        "phone": "(630) 595-0071",
        "distance_miles": 25, "direction": "W",
        "advance_booking_days": 14, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "DuPage County resident rates available.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "DuPage Golf",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Greg Martin redesign. Host of USGA events.",
    },
    "glen_club": {
        "name": "The Glen Club",
        "tier": "A+", "platform": "ezlinks",
        "booking_url": "https://theglenclub.ezlinksgolf.com/index.html#/search",
        "direct_url": "https://www.theglenclub.com",
        "chronogolf_url": "https://www.chronogolf.com/club/the-glen-club",
        "golfnow_facility_id": None,
        "phone": "(847) 724-7272",
        "distance_miles": 20, "direction": "N",
        "advance_booking_days": 7, "has_range": True, "range_included": True,
        "cancel_window_hours": 48, "cancel_type": "free_cancel",
        "cancel_details": "48hr cancel policy. Premium course.",
        "prepaid": False, "risk_tier": "medium", "walk_ride": "ride_included",
        "sub_courses": None, "management": "KemperSports",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Tom Fazio design. Former host of NCAA Championship. Premium pricing.",
    },
    "highlands_elgin": {
        "name": "Highlands of Elgin",
        "tier": "A", "platform": "proshop_teetimes",
        "booking_url": "https://booking.proshopteetimes.com/SelectPlayers.aspx?CourseID=95",
        "proshop_course_id": "95",
        "direct_url": "https://highlandsofelgin.com/book-a-tee-time/",
        "golfnow_facility_id": None,
        "phone": "(847) 931-5950",
        "distance_miles": 40, "direction": "NW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "Free cancel 24hr+.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "City of Elgin",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Greg Martin design. Solid public course.",
    },
    "bowes_creek": {
        "name": "Bowes Creek CC",
        "tier": "A", "platform": "proshop_teetimes",
        "booking_url": "https://booking.proshopteetimes.com/SelectPlayers.aspx?CourseID=94",
        "proshop_course_id": "94",
        "direct_url": "https://bowescreekcc.com/",
        "golfnow_facility_id": None,
        "phone": "(847) 931-5950",
        "distance_miles": 40, "direction": "NW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "Free cancel 24hr+.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "City of Elgin",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Rick Jacobson design. Part of Elgin golf complex with Highlands.",
    },
    "cantigny": {
        "name": "Cantigny Golf",
        "tier": "A+", "platform": "whoosh",
        "booking_url": "https://app.whoosh.io/patron/club/cantigny-golf-course/agenda/golf-course/",
        "direct_url": "https://www.cantignygolf.com",
        "golfnow_facility_id": None,
        "phone": "(630) 668-8463",
        "distance_miles": 30, "direction": "W",
        "advance_booking_days": 14, "has_range": True, "range_included": True,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel. Own booking system.",
        "prepaid": False, "risk_tier": "medium", "walk_ride": "ride_included",
        "sub_courses": ["Lakeside", "Woodside", "Hillside"],
        "management": "McCormick Foundation",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "27 holes. Lakeside/Woodside combo is the main 18. Own booking platform.",
    },
    "cog_hill_123": {
        "name": "Cog Hill #1/2/3",
        "tier": "A", "platform": "foreup",
        "booking_url": "https://foreupsoftware.com/index.php/booking/a/22487/11#/teetimes",
        "direct_url": "https://www.coghillgolf.com",
        "golfnow_facility_id": None,
        "phone": "(866) 264-4455",
        "distance_miles": 28, "direction": "SW",
        "advance_booking_days": 14, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": ["#1", "#2", "#3"], "management": "Jemsek Golf",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Great value. #2 is the best of the three.",
    },
    "cog_hill_4": {
        "name": "Cog Hill #4 (Dubsdread)",
        "tier": "A+", "platform": "foreup",
        "booking_url": "https://foreupsoftware.com/index.php/booking/a/22487/11#/teetimes",
        "direct_url": "https://www.coghillgolf.com",
        "golfnow_facility_id": None,
        "phone": "(866) 264-4455",
        "distance_miles": 28, "direction": "SW",
        "advance_booking_days": 14, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel. Premium pricing for #4.",
        "prepaid": False, "risk_tier": "medium", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Jemsek Golf",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Dubsdread. Former BMW Championship host. Best public course in Chicago.",
    },
    "mistwood": {
        "name": "Mistwood Golf Club",
        "tier": "A+", "platform": "cps_golf",
        "booking_url": "https://mistwood.cps.golf/onlineresweb/search-teetime?TeeOffTimeMin=0&TeeOffTimeMax=23",
        "direct_url": "https://mistwoodgc.com",
        "chronogolf_slug": "mistwood-golf-club-illinois",
        "phone": "(815) 254-3333",
        "distance_miles": 35, "direction": "SW",
        "advance_booking_days": 10, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": True, "autobook_eligible": True,
        "notes": "Ray Hearn design. St Andrews sod-wall bunkers. Golf Digest Renovation of the Year. NOT on GolfNow — uses Chronogolf.",
    },
    "prairie_landing": {
        "name": "Prairie Landing Golf Club",
        "tier": "A", "platform": "golfback",
        "booking_url": "https://golfback.com/#/course/dba9546a-1cdf-4c55-8abb-e8bfcb7c6c84",
        "direct_url": "https://www.prairielanding.com",
        "chronogolf_slug": "prairie-landing-golf-club",
        "golfback_id": "dba9546a-1cdf-4c55-8abb-e8bfcb7c6c84",
        "phone": "(630) 208-7600",
        "distance_miles": 35, "direction": "W",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": True, "autobook_eligible": True,
        "notes": "Robert Trent Jones Jr links-style. Golf Digest 4.5 star. NOT on GolfNow — facility 702 is Cary CC. Uses Chronogolf/GolfBack.",
    },

    # ===== NEW COURSES (26 from user's list) =====

    "arboretum": {
        "name": "Arboretum Golf Club",
        "tier": "A", "platform": "golfnow",
        "booking_url": _gn(6171, "the-arboretum-golf-club"),
        "direct_url": "https://www.arboretumgolfclub.com",
        "golfnow_facility_id": "6171",
        "phone": "(847) 913-1112",
        "distance_miles": 35, "direction": "N",
        "advance_booking_days": 7, "has_range": False, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Buffalo Grove Park District",
        "noteefy_available": True, "autobook_eligible": True,
        "notes": "Beautiful venue, no range. Great course with lots of water and challenges.",
    },
    "balmoral_woods": {
        "name": "Balmoral Woods Country Club",
        "tier": "A", "platform": "chronogolf",
        "booking_url": "https://www.chronogolf.com/club/5552/widget?medium=widget&source=club",
        "chronogolf_url": "https://www.chronogolf.com/club/5552",
        "direct_url": "https://www.balmoralwoods.com",
        "golfnow_facility_id": None,
        "phone": "(708) 672-7448",
        "distance_miles": 36, "direction": "S",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Really nice range. Very different types of holes. Golf Digest 4 star.",
    },
    "bartlett_hills": {
        "name": "Bartlett Hills Golf Club",
        "tier": "A", "platform": "direct",
        "booking_url": "https://www.bartletthills.com/teetimes/",
        "direct_url": "https://www.bartletthillsgc.com",
        "golfnow_facility_id": None,
        "phone": "(630) 837-2741",
        "distance_miles": 34, "direction": "W",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Bartlett Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "$10K 18-hole contest. Very hard greens. Lots of elevation and hills. Greatly maintained.",
    },
    "bridges_poplar": {
        "name": "Bridges of Poplar Creek CC",
        "tier": "A", "platform": "ezlinks",
        "booking_url": "https://poplarcreekccpp.ezlinksgolf.com/index.html#/search",
        "direct_url": "https://www.bridgesofpoplarcreek.com",
        "golfnow_facility_id": None,
        "phone": "(847) 884-0219",
        "distance_miles": 35, "direction": "NW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Hoffman Estates Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Nice course all around, good rate ($55). Nice fairways and greens (tough greens). Close to city.",
    },
    "broken_arrow": {
        "name": "Broken Arrow Golf Club",
        "tier": "A", "platform": "teeitup",
        "booking_url": "https://broken-arrow-golf-club.book.teeitup.com/?course=7300",
        "direct_url": "https://www.brokenarrowgc.com",
        "golfnow_facility_id": None,
        "phone": "(815) 836-8858",
        "distance_miles": 37, "direction": "SW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Lockport Township Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Great course, good quality greens & fairways. Great price. Has 27 holes.",
    },
    "chevy_chase": {
        "name": "Chevy Chase Country Club",
        "tier": "A", "platform": "direct",
        "booking_url": "https://www.traditionsatchevychase.com/tee-time/",
        "direct_url": "https://www.chevychasegolf.org",
        "golfnow_facility_id": None,
        "phone": "(847) 537-0082",
        "distance_miles": 32, "direction": "N",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Wheeling Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Very nice course. Nice fairways and greens. Good pace.",
    },
    "coyote_run": {
        "name": "Coyote Run Golf Course",
        "tier": "B+", "platform": "golfnow",
        "booking_url": "https://www.golfnow.com/tee-times/facility/700-coyote-run-golf-course-il/search",
        "direct_url": "https://www.coyoterungolf.com",
        "golfnow_facility_id": "700",
        "phone": "(708) 957-8700",
        "distance_miles": 27, "direction": "S",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Fun and easy course. Has a range.",
    },
    "deerfield": {
        "name": "Deerfield Golf Course",
        "tier": "A", "platform": "golfnow",
        "booking_url": _gn(5435, "deerfield-golf-club"),
        "direct_url": "https://www.deerfieldgolf.org",
        "golfnow_facility_id": "5435",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Great course, good price ($50). Long and short range. Carts have computers.",
    },
    "fox_run": {
        "name": "Fox Run Golf Course",
        "tier": "A", "platform": "direct",
        "booking_url": "https://www.foxrungolflinks.com/tee-times/",
        "direct_url": "https://www.foxrungolflinks.com",
        "golfnow_facility_id": None,
        "phone": "(847) 228-3544",
        "distance_miles": 29, "direction": "W",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Elk Grove Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Nice course. Well maintained. New clubhouse.",
    },
    "foxford_hills": {
        "name": "Foxford Hills Golf Club",
        "tier": "A+", "platform": "golfnow",
        "booking_url": _gn(841, "foxford-hills-golf-club"),
        "direct_url": "https://www.foxfordhills.com",
        "golfnow_facility_id": "841",
        "phone": "(847) 639-0400",
        "distance_miles": 45, "direction": "NW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "A+ course. Tough with various layouts. Kinda far out but awesome.",
    },
    "george_dunne": {
        "name": "George Dunne National GC",
        "tier": "A", "platform": "golfnow",
        "booking_url": "https://www.golfnow.com/tee-times/facility/3316-george-w-dunne-national-golf-course/search",
        "direct_url": "https://www.fpdcc.com/places/locations/george-w-dunne-national-golf-course/",
        "golfnow_facility_id": "3316",
        "phone": "(708) 429-6886",
        "distance_miles": 25, "direction": "S",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Cook County Forest Preserve",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Good, challenging course. Really good fairways, greens, tboxes. Has range and cart girls.",
    },
    "green_garden": {
        "name": "Green Garden Country Club",
        "tier": "A", "platform": "direct",
        "booking_url": "https://www.greengardencc.com/teetimes/",
        "direct_url": "https://www.greengardencc.com",
        "golfnow_facility_id": None,
        "phone": "(815) 469-3350",
        "distance_miles": 39, "direction": "S",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Huge golf complex. 45 holes.",
    },
    "hilldale": {
        "name": "Hilldale Golf Club",
        "tier": "A", "platform": "teeitup",
        "booking_url": "https://hilldale-golf-club.book.teeitup.com/?course=4855",
        "direct_url": "https://www.hilldalegolf.com",
        "golfnow_facility_id": None,
        "phone": "(847) 310-1100",
        "distance_miles": 35, "direction": "NW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Hoffman Estates Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Very challenging. Tons of water. Perfect in warm summer.",
    },
    "links_carillon": {
        "name": "The Links at Carillon",
        "tier": "A", "platform": "ezlinks",
        "booking_url": "https://carillon.ezlinksgolf.com/index.html#/search",
        "direct_url": "https://www.carillongolf.com",
        "golfnow_facility_id": None,
        "phone": "(815) 886-2132",
        "distance_miles": 34, "direction": "SW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "27 hole course. Nice neighborhood layout. Good quality. Found it for $60pp.",
    },
    "lost_marsh": {
        "name": "Lost Marsh Golf Course",
        "tier": "A", "platform": "direct",
        "booking_url": "https://www.lostmarshgolf.com/teetimes/",
        "direct_url": "https://www.lostmarsh.com",
        "golfnow_facility_id": None,
        "phone": "(219) 932-4653",
        "distance_miles": 25, "direction": "SE",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "City of Hammond",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Upgraded to A course. Close to city. Electric carts. Fun layout. Little expensive.",
    },
    "makray": {
        "name": "Makray Memorial Golf Club",
        "tier": "A", "platform": "golfnow",
        "booking_url": _gn(847, "makray-memorial-golf-club"),
        "direct_url": "https://www.makraygolf.com",
        "golfnow_facility_id": "847",
        "phone": "(847) 381-6500",
        "distance_miles": 38, "direction": "NW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": True, "autobook_eligible": True,
        "notes": "Good course. Well maintained. Gives free waters. Has range.",
    },
    "pine_meadow": {
        "name": "Pine Meadow Golf Course",
        "tier": "A", "platform": "golfnow",
        "booking_url": "https://www.golfnow.com/tee-times/facility/3300-pine-meadow/search",
        "direct_url": "https://www.pinemeadowgc.com",
        "golfnow_facility_id": "3300",
        "phone": "(847) 566-4653",
        "distance_miles": 41, "direction": "N",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Great course. Has a range. Great quality.",
    },
    "prairie_bluff": {
        "name": "Prairie Bluff Golf Course",
        "tier": "A-", "platform": "chronogolf",
        "booking_url": "https://www.chronogolf.com/club/prairie-bluff-golf-club",
        "direct_url": "https://www.prairiebluff.com",
        "golfnow_facility_id": None,
        "phone": "(815) 836-4653",
        "distance_miles": 36, "direction": "SW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Lockport Township Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Really well maintained and pretty. Playable, not too challenging. Very long rough and far away.",
    },
    "ruffled_feathers": {
        "name": "Ruffled Feathers Golf Club",
        "tier": "A", "platform": "golfnow",
        "booking_url": "https://www.golfnow.com/tee-times/facility/945-ruffled-feathers-golf-club/search",
        "direct_url": "https://www.ruffledfeathersgc.com",
        "golfnow_facility_id": "945",
        "phone": "(630) 257-1000",
        "distance_miles": 28, "direction": "SW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Arcis Golf",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Next to Cog Hill. Tough course, hard to score on. Thick long rough. Challenging greens. Pete Dye design.",
    },
    "st_andrews": {
        "name": "St. Andrews Golf Club",
        "tier": "A", "platform": "teeitup",
        "booking_url": "https://st-andrews-golf-club-chicago-v2.book.teeitup.com/?course=3299,5038",
        "direct_url": "https://www.standrewsgc.com",
        "golfnow_facility_id": None,
        "phone": "(630) 231-3100",
        "distance_miles": 37, "direction": "W",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Great course. Cool holes. Fun & challenging. Good quality. Solid A course. Only issue is far (50+min).",
    },
    "seven_bridges": {
        "name": "Seven Bridges Golf Club",
        "tier": "A+", "platform": "golfnow",
        "booking_url": "https://www.golfnow.com/tee-times/facility/827-seven-bridges-golf-club/search",
        "direct_url": "https://www.sevenbridgesgolfclub.com",
        "golfnow_facility_id": "827",
        "phone": "(630) 964-7777",
        "distance_miles": 28, "direction": "W",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "medium", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Woodridge Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Really hard. Tough Back 9, tons of water. Golf Digest 4-star. Top 5 public course in Chicago.",
    },
    "sunset_valley": {
        "name": "Sunset Valley Golf Course",
        "tier": "B+", "platform": "foreup",
        "booking_url": "https://foreupsoftware.com/index.php/booking/21000/6510#/teetimes",
        "direct_url": "https://www.sunsetvalleygolfcourse.org",
        "golfnow_facility_id": None,
        "phone": "(847) 432-7140",
        "distance_miles": 25, "direction": "N",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Highland Park Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Fun local course.",
    },
    "waters_edge": {
        "name": "Water's Edge Golf Course",
        "tier": "A", "platform": "golfnow",
        "booking_url": "https://www.golfnow.com/tee-times/facility/2408-waters-edge-golf-club/search",
        "direct_url": "https://www.watersedgegolf.com",
        "golfnow_facility_id": "2408",
        "phone": "(708) 671-1032",
        "distance_miles": 20, "direction": "SW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "Independent",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Grass range, nice rangers, good carts. Nice variation of holes. Fun but challenging.",
    },
    "sanctuary": {
        "name": "Sanctuary Golf Course",
        "tier": "A", "platform": "foreup",
        "booking_url": "https://foreupsoftware.com/index.php/booking/21043/6838#teetimes",
        "direct_url": "https://www.golfsanctuary.com",
        "golfnow_facility_id": None,
        "phone": "(815) 462-4653",
        "distance_miles": 35, "direction": "SW",
        "advance_booking_days": 7, "has_range": True, "range_included": False,
        "cancel_window_hours": 24, "cancel_type": "free_cancel",
        "cancel_details": "24hr cancel.",
        "prepaid": False, "risk_tier": "low", "walk_ride": "ride_included",
        "sub_courses": None, "management": "New Lenox Community Park District",
        "noteefy_available": False, "autobook_eligible": False,
        "notes": "Good value course in New Lenox.",
    },
}


def get_course(course_id: str) -> dict:
    return COURSES.get(course_id)


def get_all_courses() -> dict:
    return COURSES


def get_courses_by_platform(platform: str) -> list:
    return [
        {**v, "id": k}
        for k, v in COURSES.items()
        if v["platform"] == platform
    ]


def get_autobook_safe_courses() -> list:
    """Courses where auto-booking is safe (low risk, on GolfNow)."""
    return [
        {**v, "id": k}
        for k, v in COURSES.items()
        if v.get("risk_tier", "low") == "low" and v.get("platform") in ("golfnow", "chronogolf")
    ]


def get_deep_link_only_courses() -> list:
    """Courses that should only get alert + deep link."""
    return [
        {**v, "id": k}
        for k, v in COURSES.items()
        if v.get("risk_tier") == "high" or v.get("platform") == "custom"
    ]


def get_scraper_method(course_id: str) -> str:
    """Return which scraper covers this course."""
    c = COURSES.get(course_id, {})
    if c.get("platform") == "golfnow" and c.get("golfnow_facility_id"):
        return "golfnow"
    if c.get("platform") == "chronogolf":
        return "chronogolf"
    if c.get("platform") == "foreup":
        return "foreup"
    return "direct"


def get_all_scrapable_courses() -> list:
    """All courses that have a working scraper path."""
    return [
        {**v, "id": k, "scraper": get_scraper_method(k)}
        for k, v in COURSES.items()
    ]
